on: push
jobs:
  getShortSha:
    runs-on: ubuntu-latest
    outputs:
      shortSha: ${{ steps.get_short_sha.outputs.shortSha }}
    steps:
      - id: get_short_sha
        run: |
          commitSha="${{github.sha}}"
          echo "::set-output name=shortSha::${commitSha:0:6}"
  # checkout:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/cache@v3
  #       with:
  #         path: .
  #         key: ${{ runner.os }}-${{ github.ref_name }}-code

  # install-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/cache@v3
  #       name: cache-prod-modules
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-${{ github.ref_name }}-prod
  #     - if: ${{ steps.cache-prod-modules.outputs.cache-hit != 'true' }}
  #       run: npm install --omit=dev
  install:
    runs-on: ubuntu-latest
    needs: getShortSha
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ needs.getShortSha.outputs.shortSha }}-${{ github.ref_name }}-modules
      - if: ${{ steps.cache-prod-modules.outputs.cache-hit != 'true' }}
        run: npm install
  build:
    runs-on: ubuntu-latest
    needs:
      - install
      - getShortSha
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        name: cache-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ needs.getShortSha.outputs.shortSha }}-${{ github.ref_name }}
      - run: npm run build
      - uses: actions/upload-artifact@v3
        with:
          name: build-dist
          path: dist
          if-no-files-found: error